// Generated by CoffeeScript 1.6.1
(function() {
  var count, end, move, start, timeout;

  end = move = start = {};

  count = timeout = null;

  document.addEventListener('touchstart', function(event) {
    start = event;
    if (!(start.timeStamp - end.timeStamp < 350)) {
      count = 0;
    }
    if (timeout != null) {
      return clearTimeout(timeout);
    }
  });

  document.addEventListener('touchmove', function(event) {
    return move = event;
  });

  document.addEventListener('touchend', function(event) {
    var fn;
    end = event;
    ++count;
    if (end.timeStamp - start.timeStamp < 1) {
      return;
    }
    if (end.timeStamp - start.timeStamp > 600) {
      return;
    }
    if (move.timeStamp > start.timeStamp) {
      return;
    }
    event = new CustomEvent("tap" + count, {
      bubbles: true,
      cancelable: true
    });
    fn = function() {
      return start.target.dispatchEvent(event);
    };
    return timeout = setTimeout(fn, 300);
  });

}).call(this);
